apiVersion: v1
data:
  MYSQL_DB: R2lmdGNhcmRTaXRlREI=
  MYSQL_ROOT_PASSWORD: dGhpc2lzYXRlc3R0aGluZy4=
kind: Secret
metadata:
  creationTimestamp: "2020-12-17T04:23:03Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:MYSQL_DB: {}
        f:MYSQL_ROOT_PASSWORD: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2020-12-17T04:23:03Z"
  name: mysql-secret
  namespace: default
  resourceVersion: "882"
  selfLink: /api/v1/namespaces/default/secrets/mysql-secret
  uid: 407a7f4c-d0e5-47c6-9b10-5da7f42bf7f8
type: Opaque
